name: CI/CD Flask Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout
        uses: actions/checkout@v3

  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

    
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      # 🚀 Deploy to EC2 (FIXED)
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull latest image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

            # Stop & remove old container
            sudo docker stop flask-container || true
            sudo docker rm flask-container || true

            # Run new container WITH ENV VARIABLES ✅
            sudo docker run -d \
              -p 5000:8000 \
              --name flask-container \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

            # Show running containers
            sudo docker ps